# API
api:
  # restTemplate
  connect:
    connect-timeout: 5000
    read-timeout: 5000
  # fruit
  fruit:
    api-prefix: http://fruit.***.net
# fruit
  vegetable:
    api-prefix: http://vegetable.***.net